# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- ddd

variables:
  versionNumber: 'vers.1'  # Sie können die Nummer hier manuell setzen oder dynamisch generieren

jobs:
- job: CopyAndZipFiles
  steps:
  - checkout: self

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/test'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/test.zip'
      replaceExistingArchive: true

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: 'test.zip'
      TargetFolder: '/home/memet/azagent/Test'
      CleanTargetFolder: true
      OverWrite: true

  - script: echo "Version Number:$(versionNumber)"
    displayName: 'Display Version Number'
